/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6wilmerjosue11511242;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author macbookpro
 */
public class BaleadasBinarias extends javax.swing.JFrame {

    /**
     * Creates new form BaleadasBinarias
     */
    public BaleadasBinarias() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jd_info = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_clientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jd_agregaror = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jl_numero = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_orden = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        cb_baleadas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jd_cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_dinero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_direccion = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jd_eliminarc = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_eliminar = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        pop_menu = new javax.swing.JPopupMenu();
        popm_orden = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setViewportView(jl_clientes);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(arbol);

        jButton2.setText("Mostrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton2)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setText("info.Cliente");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("Cliente");

        javax.swing.GroupLayout jd_infoLayout = new javax.swing.GroupLayout(jd_info.getContentPane());
        jd_info.getContentPane().setLayout(jd_infoLayout);
        jd_infoLayout.setHorizontalGroup(
            jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
            .addGroup(jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_infoLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel3)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );
        jd_infoLayout.setVerticalGroup(
            jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_infoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_infoLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel3)
                    .addContainerGap(336, Short.MAX_VALUE)))
        );

        jLabel1.setText("Numero de orden");

        jl_numero.setText("000");

        jScrollPane3.setViewportView(jl_orden);

        jLabel5.setText("Seleccione Cliente");

        cb_baleadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baleadas Binarias", "Baleadas Especiales", "Baleadas Reloaded", "Baleadas OutOfBounds", " " }));

        jButton1.setText("Agregar ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton5.setText("Finalizar orden");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarorLayout = new javax.swing.GroupLayout(jd_agregaror.getContentPane());
        jd_agregaror.getContentPane().setLayout(jd_agregarorLayout);
        jd_agregarorLayout.setHorizontalGroup(
            jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(jl_numero))
                    .addGroup(jd_agregarorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarorLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(cb_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarorLayout.setVerticalGroup(
            jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jl_numero))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregarorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_agregarorLayout.createSequentialGroup()
                        .addComponent(cb_baleadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel7.setText("Agregar Cliente");

        jLabel8.setText("Nombre");

        jLabel9.setText("Numero de telefono");

        jLabel10.setText("Dinero Bolsa");

        tf_dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dineroActionPerformed(evt);
            }
        });

        jLabel11.setText("Direccion ");

        ta_direccion.setColumns(20);
        ta_direccion.setRows(5);
        jScrollPane5.setViewportView(ta_direccion);

        jButton3.setText("Agregar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_clienteLayout = new javax.swing.GroupLayout(jd_cliente.getContentPane());
        jd_cliente.getContentPane().setLayout(jd_clienteLayout);
        jd_clienteLayout.setHorizontalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel7))
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(67, 67, 67)
                        .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(85, 85, 85)
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_clienteLayout.setVerticalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jl_eliminar);

        jLabel12.setText("Seleccione Cliente ");

        jButton4.setText("Eliminar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarcLayout = new javax.swing.GroupLayout(jd_eliminarc.getContentPane());
        jd_eliminarc.getContentPane().setLayout(jd_eliminarcLayout);
        jd_eliminarcLayout.setHorizontalGroup(
            jd_eliminarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarcLayout.createSequentialGroup()
                .addGroup(jd_eliminarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminarcLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_eliminarcLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel12))
                    .addGroup(jd_eliminarcLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jd_eliminarcLayout.setVerticalGroup(
            jd_eliminarcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarcLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        popm_orden.setText("Terminar Orden");
        pop_menu.add(popm_orden);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Baleadas Binarias");

        jMenu4.setText("Clientes");

        jMenuItem2.setText("Agregar Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jMenu4.add(Modificar);

        jMenuItem3.setText("Eliminar Cliente");
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu5.setText("Ordenes");

        jMenuItem4.setText("Agregar Orden");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Info. Ordenes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_dineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dineroActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (tf_nombre.getText().length() > 0 && tf_telefono.getText().length() > 0 && tf_dinero.getText().length() > 0 && ta_direccion.getText().length() > 0) {
            lista.add(new Clientes(tf_nombre.getText(), Integer.parseInt(tf_telefono.getText()), Double.parseDouble(tf_dinero.getText()), ta_direccion.getText()));
            tf_nombre.setText("");
            tf_telefono.setText("");
            tf_dinero.setText("");
            ta_direccion.setText("");
            JOptionPane.showMessageDialog(this, "Cliente agregado");

        } else {
            JOptionPane.showMessageDialog(this, "Complete Todos los espacios");
            jd_cliente.setVisible(true);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_cliente.pack();
        jd_cliente.setLocationRelativeTo(this);
        jd_cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String t = "" + numero;
        jl_numero.setText(t);
        jd_agregaror.pack();
        jd_agregaror.setLocationRelativeTo(this);
        jd_agregaror.setVisible(true);
        DefaultListModel modelo = new DefaultListModel();
        for (Clientes c : lista) {
            modelo.addElement(new Clientes(c.getNombre(), c.getNumero(), c.getDinero(), c.getDireccion()));
        }
        jl_orden.setModel(modelo);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (jl_orden.getSelectedIndex() >= 0) {
            baleadas.add(cb_baleadas.getSelectedItem().toString());
            JOptionPane.showMessageDialog(jd_agregaror, "Baleada Agregada");
        } else {
            JOptionPane.showMessageDialog(jd_agregaror, "Seleccione una persona");

        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if (jl_orden.getSelectedIndex() >= 0) {
            for (String t : baleadas) {
                lista.get(jl_orden.getSelectedIndex()).getLista().add(t);
            }
            ArrayList<String> baleadas = new ArrayList();
        } else {
            JOptionPane.showMessageDialog(jd_agregaror, "Seleccione una persona");
        }
        SimpleDateFormat hora = new SimpleDateFormat("hh");
        SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yy");
        listas.add(new Ordenes(numero, hora, fecha, jl_orden.getSelectedIndex()));
        numero += 7;
        JOptionPane.showMessageDialog(this, "Orden Finalizada");

    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jd_info.pack();
        jd_info.setLocationRelativeTo(this);
        jd_info.setVisible(true);
        DefaultListModel modelo = new DefaultListModel();
        for (Clientes c : lista) {
            modelo.addElement(new Clientes(c.getNombre(), c.getNumero(), c.getDinero(), c.getDireccion()));
        }
        jl_clientes.setModel(modelo);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (jl_clientes.getSelectedIndex() >= 0) {
            boolean hayorden = false;
            int posision = jl_clientes.getSelectedIndex();
            for (Ordenes c : listas) {
                if (c.getPersona() == posision) {
                    hayorden = true;
                }
            }
            DefaultTreeModel modeloarbol = (DefaultTreeModel) arbol.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloarbol.getRoot();
            String nombre = lista.get(posision).getNombre();
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(nombre);
            n.add(new DefaultMutableTreeNode("Numero De telefono" + lista.get(posision).getNumero()));
            n.add(new DefaultMutableTreeNode("Dinero" + lista.get(posision).getDinero()));
            n.add(new DefaultMutableTreeNode("Direccion" + lista.get(posision).getDireccion()));
            DefaultMutableTreeNode ne = new DefaultMutableTreeNode(new Ordenes());
            for (int i = 0; i < lista.get(posision).getLista().size(); i++) {
                DefaultMutableTreeNode t = new DefaultMutableTreeNode(lista.get(posision).getLista().get(i));
                if (lista.get(posision).getLista().get(i).equals("Baleadas Binarias")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode("Tortilla");
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mantequilla");
                    DefaultMutableTreeNode fri = new DefaultMutableTreeNode("frijoles");
                    t.add(p);
                    t.add(m);
                    t.add(fri);
                }
                if (lista.get(posision).getLista().get(i).equals("Baleadas Especiales")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode("Tortilla");
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mantequilla");
                    DefaultMutableTreeNode fri = new DefaultMutableTreeNode("frijoles");
                    DefaultMutableTreeNode huevo = new DefaultMutableTreeNode("huevo");
                    t.add(p);
                    t.add(m);
                    t.add(fri);
                    t.add(huevo);
                }
                if (lista.get(posision).getLista().get(i).equals("Baleadas Reloaded")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode("Tortilla");
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mantequilla");
                    DefaultMutableTreeNode fri = new DefaultMutableTreeNode("frijoles");
                    DefaultMutableTreeNode huevo = new DefaultMutableTreeNode("huevo");
                    DefaultMutableTreeNode pla = new DefaultMutableTreeNode("pla");
                    t.add(p);
                    t.add(m);
                    t.add(fri);
                    t.add(huevo);
                    t.add(pla);
                }
                if (lista.get(posision).getLista().get(i).equals("Baleadas OutOfBounds")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode("Tortilla");
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mantequilla");
                    DefaultMutableTreeNode fri = new DefaultMutableTreeNode("frijoles");
                    DefaultMutableTreeNode huevo = new DefaultMutableTreeNode("Huevo");
                    DefaultMutableTreeNode pla = new DefaultMutableTreeNode("Platano");
                    DefaultMutableTreeNode chorizo = new DefaultMutableTreeNode("Chorizo");
                    t.add(p);
                    t.add(m);
                    t.add(fri);
                    t.add(huevo);
                    t.add(pla);
                    t.add(chorizo);
                }
                ne.add(t);
                n.add(ne);

            }

            raiz.add(n);
            modeloarbol.reload();

        } else {
            JOptionPane.showMessageDialog(jd_info, "Seleccione Persona");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            arbol.setSelectionRow(row);
            Object v1 = arbol.getSelectionRows();
            nodo_selecionado = (DefaultMutableTreeNode) v1;
            if (nodo_selecionado.getUserObject() instanceof Ordenes) {
                persona_seleccionada = (Clientes) nodo_selecionado.getUserObject();
                pop_menu.show(evt.getComponent(), evt.getY(), evt.getX());
            }
        } else {
        }
    }//GEN-LAST:event_arbolMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:\
        
        DefaultListModel modelo = new DefaultListModel();
        for (Clientes c : lista) {
            modelo.addElement(new Clientes(c.getNombre(), c.getNumero(), c.getDinero(), c.getDireccion()));
        }
        jl_orden.setModel(modelo);
        int posicio = jl_eliminar.getSelectedIndex();
        lista.remove(posicio);
        for (Clientes c : lista) {
            modelo.addElement(new Clientes(c.getNombre(), c.getNumero(), c.getDinero(), c.getDireccion()));
        }
        jl_orden.setModel(modelo);
    }//GEN-LAST:event_jButton4MouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        jd_eliminarc.pack();
        jd_eliminarc.setLocationRelativeTo(this);
        jd_eliminarc.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaleadasBinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaleadasBinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaleadasBinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaleadasBinarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaleadasBinarias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTree arbol;
    private javax.swing.JComboBox<String> cb_baleadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog jd_agregaror;
    private javax.swing.JDialog jd_cliente;
    private javax.swing.JDialog jd_eliminarc;
    private javax.swing.JDialog jd_info;
    private javax.swing.JList<String> jl_clientes;
    private javax.swing.JList<String> jl_eliminar;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JList<String> jl_orden;
    private javax.swing.JPopupMenu pop_menu;
    private javax.swing.JMenuItem popm_orden;
    private javax.swing.JTextArea ta_direccion;
    private javax.swing.JTextField tf_dinero;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
ArrayList<Clientes> lista = new ArrayList();
    ArrayList<String> baleadas = new ArrayList();
    ArrayList<Ordenes> listas = new ArrayList();
    int numero = 7;
    DefaultMutableTreeNode nodo_selecionado;
    Clientes persona_seleccionada;
}
